server:
  port: 9001
#数据库连接信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#mybatis包扫描
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dailywear.base_structure.common.entity

#配置日志
logging:
  #此处存放日志的路径
  path:
    config: classpath:logback.xml
  #指定不同目录下的日志的级别
  level:
    com:
      dailywear:
        base_structure:
          mapper: INFO